# Generated by Django 3.2.5 on 2021-09-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.IntegerField(help_text="object's id on which the notification was generated.", null=True),
        ),
    ]
