version: "3.9"
   
services:
  rabbitmq:
    image: rabbitmq:3.9.0-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:14.0-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=Clon-Facebook
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  django:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment: 
      - CELERY_BROKER_URL=amqp://rabbitmq
    depends_on:
      - postgres
    command: /code/compose/django/start.sh

  celeryworker:
    build: .
    volumes:
        - .:/code
    ports: []
    depends_on:
        - rabbitmq
    command: /code/compose/celery/worker/start.sh
        
  celerybeat:
    build: .
    volumes:
        - .:/code
    ports: []
    depends_on:
        - rabbitmq
        - celeryworker
    command: /code/compose/celery/beat/start.sh

volumes:
  postgres:

