# Generated by Django 3.2.5 on 2021-08-02 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20210802_0136'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the was las modified.', verbose_name='modified at')),
                ('about', models.CharField(blank=True, help_text='write something', max_length=350)),
                ('picture', models.ImageField(blank=True, help_text='post picture', null=True, upload_to='posts/pictures/')),
                ('privacy', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends'), ('FRIENDS_EXC', 'Friends_except'), ('SPECIFIC_FRIENDS', 'Specific_friends')], default='FRIENDS', help_text='privacy of post', max_length=16)),
                ('feeling', models.CharField(blank=True, choices=[('HAPPY', 'happy'), ('LOVED', 'loved'), ('EXCITED', 'excited'), ('CRAZY', 'crazy'), ('THANKFUL', 'thankful'), ('FANTASTIC', 'fantastic'), ('MOTIVED', 'motived'), ('TIRED', 'tired'), ('ALONE', 'alone'), ('ANGRY', 'angry'), ('SORRY', 'sorry'), ('CONFUSED', 'confused'), ('STRONG', 'strong'), ('STRESSED', 'stressed'), ('SCARED', 'scared')], help_text='how you feel', max_length=9)),
                ('location', models.CharField(blank=True, help_text='where are you?', max_length=60)),
                ('reactions', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('tag_friends', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
