# Generated by Django 3.2.5 on 2021-08-21 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the was las modified.', verbose_name='modified at')),
                ('text', models.TextField(help_text='write a comment', max_length=250)),
                ('reactions', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the was las modified.', verbose_name='modified at')),
                ('about', models.CharField(blank=True, help_text='write something', max_length=350)),
                ('picture', models.ImageField(blank=True, help_text='post picture', null=True, upload_to='posts/pictures/')),
                ('privacy', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends'), ('FRIENDS_EXC', 'Friends_except'), ('SPECIFIC_FRIENDS', 'Specific_friends')], default='FRIENDS', help_text='privacy of post', max_length=16)),
                ('feeling', models.CharField(blank=True, choices=[('HAPPY', 'happy'), ('LOVED', 'loved'), ('EXCITED', 'excited'), ('CRAZY', 'crazy'), ('THANKFUL', 'thankful'), ('FANTASTIC', 'fantastic'), ('MOTIVED', 'motived'), ('TIRED', 'tired'), ('ALONE', 'alone'), ('ANGRY', 'angry'), ('SORRY', 'sorry'), ('CONFUSED', 'confused'), ('STRONG', 'strong'), ('STRESSED', 'stressed'), ('SCARED', 'scared')], help_text='how you feel', max_length=9)),
                ('location', models.CharField(blank=True, help_text='where are you?', max_length=60)),
                ('reactions', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('destination', models.CharField(choices=[('FRIEND', 'friend'), ('GROUP', 'group'), ('BIOGRAPHY', 'biography'), ('PAGE', 'page')], default='BIOGRAPHY', help_text='specify if the post will be published in a group, page, biography of a friend or in your biography', max_length=9)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ReactionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the was las modified.', verbose_name='modified at')),
                ('reaction', models.CharField(choices=[('LIKE', 'like'), ('LOVE', 'love'), ('CARE', 'care'), ('HAHA', 'haha'), ('SAD', 'sad'), ('ANGRY', 'angry')], help_text='react to a comment', max_length=5)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReactionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the was las modified.', verbose_name='modified at')),
                ('reaction', models.CharField(choices=[('LIKE', 'like'), ('LOVE', 'love'), ('CARE', 'care'), ('HAHA', 'haha'), ('SAD', 'sad'), ('ANGRY', 'angry')], help_text='react to a post', max_length=5)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
