# Generated by Django 3.2.5 on 2021-08-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='post video', null=True, upload_to='posts/videos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='feeling',
            field=models.CharField(blank=True, choices=[('HAPPY', 'happy'), ('LOVED', 'loved'), ('EXCITED', 'excited'), ('CRAZY', 'crazy'), ('THANKFUL', 'thankful'), ('FANTASTIC', 'fantastic'), ('MOTIVED', 'motived'), ('TIRED', 'tired'), ('ALONE', 'alone'), ('ANGRY', 'angry'), ('SORRY', 'sorry'), ('CONFUSED', 'confused'), ('STRONG', 'strong'), ('STRESSED', 'stressed'), ('SCARED', 'scared'), ('SICK', 'sick'), ('SARCASTIC', 'sarcastic'), ('ANXIOUS', 'anxious')], help_text='how you feel', max_length=9),
        ),
    ]
