# Generated by Django 3.2.5 on 2021-08-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
        migrations.AddField(
            model_name='post',
            name='destination',
            field=models.CharField(choices=[('FRIEND', 'friend'), ('GROUP', 'group'), ('BIOGRAPHY', 'biography'), ('PAGE', 'page')], default='BIOGRAPHY', help_text='specify if the post will be published in a group, page, biography of a friend or in your biography', max_length=9),
        ),
    ]
