# Generated by Django 3.2.5 on 2021-08-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210822_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name_destination',
            field=models.CharField(blank=True, help_text="name of post's destination", max_length=60),
        ),
    ]
