# Generated by Django 3.2.5 on 2021-08-03 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('posts', '0003_reactioncomment_reactionpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='specify if the post will be published in a group or in the feed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group'),
        ),
    ]
