# Generated by Django 3.2.5 on 2021-08-30 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_categorysaved_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='re_post',
            field=models.ForeignKey(help_text='post to be republished', null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.post'),
        ),
    ]
