# Generated by Django 3.2.5 on 2021-09-06 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_auto_20210903_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='friends_exc',
            field=models.ManyToManyField(blank=True, related_name='friends_exc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='specific_friends',
            field=models.ManyToManyField(blank=True, related_name='specific_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag_friends',
        ),
        migrations.AddField(
            model_name='post',
            name='tag_friends',
            field=models.ManyToManyField(blank=True, related_name='tag_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
