# Generated by Django 3.2.5 on 2021-09-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Only active users are allowed to interact in the group.'),
        ),
    ]
