# Generated by Django 3.2.5 on 2021-09-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_membership_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='about',
            field=models.CharField(blank=True, help_text='group description', max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public groups can be found by other users'),
        ),
    ]
