# Generated by Django 3.2.5 on 2021-09-16 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fbpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the was las modified.', verbose_name='modified at')),
                ('used', models.BooleanField(default=False)),
                ('guest_user', models.ForeignKey(help_text='User that used the invitation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_user', to=settings.AUTH_USER_MODEL)),
                ('inviting_user', models.ForeignKey(help_text='User that is providing the invitation.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
