# Generated by Django 3.2.5 on 2021-09-16 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbpages', '0002_pageinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinvitation',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fbpages.page'),
        ),
    ]
