# Generated by Django 3.2.5 on 2021-08-01 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the was las modified.', verbose_name='modified at')),
                ('work', models.CharField(blank=True, help_text='your current job', max_length=100)),
                ('education', models.CharField(blank=True, help_text='last studies', max_length=100)),
                ('current_city', models.CharField(blank=True, help_text='city \u200b\u200bwhere you currently live', max_length=60)),
                ('web_site', models.URLField(blank=True, help_text='personal web site')),
                ('social_links', models.URLField(blank=True, help_text='social media', max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the was las modified.', verbose_name='modified at')),
                ('photo', models.ImageField(blank=True, help_text='profile photo', null=True, upload_to='users/photos/')),
                ('cover_photo', models.ImageField(blank=True, help_text='profile cover photo', null=True, upload_to='users/cover_photos/')),
                ('about', models.TextField(blank=True, help_text='write something about you')),
                ('hobby', models.CharField(blank=True, help_text='your hobbies', max_length=100)),
                ('birth_date', models.DateTimeField(blank=True, help_text='date of birth', null=True)),
                ('origin_country', models.CharField(blank=True, help_text='your country of origin', max_length=60)),
                ('datails', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profiledetail')),
                ('followers', models.ManyToManyField(blank=True, null=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, null=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
