# Generated by Django 3.2.5 on 2021-08-07 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210802_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +99 9999999999. Up to indicative + 10 digits allowed.', regex='^\\+1?\\d{1,4}[ ]\\d{10}$')]),
        ),
    ]
